sudo: required

services:
  - docker
jobs:
  include:
    - language: java
#      put back when travis fixed
#      jdk: openjdk17

      before_install:
        #  remove after travis fixed
        - java -version
        - sudo apt-get -y remove default-jdk
        - sudo apt -y autoremove
        - curl -s "https://get.sdkman.io" | bash
        - source "$HOME/.sdkman/bin/sdkman-init.sh"
        - sdk install java 17.0.2-open
        - java -version
        - export JAVA_HOME=`/usr/libexec/java_home -v 17`; java -version
        - wget https://archive.apache.org/dist/maven/maven-3/3.8.4/binaries/apache-maven-3.8.4-bin.zip
        - unzip -qq apache-maven-3.8.4-bin.zip
        - export M2_HOME=$PWD/apache-maven-3.8.4
        - export PATH=$M2_HOME/bin:$PATH
        # remove down to here#  remove after travis fixed
        - make check-mvn
        - docker login -u "${DOCKER_GCP_USERNAME}" -p "${DOCKER_GCP_PASSWORD}" https://europe-west2-docker.pkg.dev;
        - docker login -u "${DOCKERHUB_USERNAME}" -p "${DOCKERHUB_PASSWORD}";
        - docker network create ssdcrmdockerdev_default
        - echo "$DOCKER_GCP_PASSWORD" > ~/google-service-account-key.json
        - export GOOGLE_APPLICATION_CREDENTIALS=~/google-service-account-key.json

      install: echo "SKIPPING DEFAULT INSTALL" # Travis has a default maven install. Don't build twice!

      script: travis_wait mvn verify jacoco:report

      after_success:
        - gpg --no-default-keyring --keyring trustedkeys.gpg --import codecov_public_key.asc
        - curl -Os https://uploader.codecov.io/latest/linux/codecov
        - curl -Os https://uploader.codecov.io/latest/linux/codecov.SHA256SUM
        - curl -Os https://uploader.codecov.io/latest/linux/codecov.SHA256SUM.sig

        # NOTE: the "|| exit 1"'s are required to stop travis continuing to run subsequent steps even if the integrity checks failed
        - gpgv codecov.SHA256SUM.sig codecov.SHA256SUM || exit 1
        - shasum -a 256 -c codecov.SHA256SUM || exit 1

        - chmod +x codecov
        - ./codecov

      cache:
        directories:
          - $HOME/.m2

    - language: node_js
      node_js: 14

      before_install:
        - make format-check-ui

      script:
        - make test-ui

branches:
  only:
    - main
