sudo: required

services:
  - docker
jobs:
  include:
    - language: java
      jdk: openjdk11

      before_install:
        - make format-check-mvn
        - docker login -u "${DOCKER_GCP_USERNAME}" -p "${DOCKER_GCP_PASSWORD}" "${DOCKER_GCP_REGISTRY}";
        - echo "$DOCKER_GCP_PASSWORD" > ~/google-service-account-key.json
        - export GOOGLE_APPLICATION_CREDENTIALS=~/google-service-account-key.json

      install: echo "SKIPPING DEFAULT INSTALL" # Travis has a default maven install. Don't build twice!

      script: travis_wait mvn verify jacoco:report

      after_success:
        - bash <(curl -s https://codecov.io/bash)

      cache:
        directories:
          - $HOME/.m2

    - language: node_js
      node_js: 14

      before_install:
        - make format-check-ui

      script: make test-ui

branches:
  only:
    - main