server:
  port: 7777

info:
  app:
    name: Response Operations
    version: 1.0

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

  datasource:
    url: jdbc:postgresql://localhost:6432/postgres?readOnly=true
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    hikari:
      maximumPoolSize: 50
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: casev3
        jdbc:
          batch_size: 500
          order_inserts: true
          lob:
            non_contextual_creation: true

  task:
    scheduling:
      pool:
        size: 10

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

logging:
  profile: DEV
  level:
    ROOT: INFO

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
  metrics:
    tags:
      application: Support Tool
      pod: ${HOSTNAME}
    export:
      stackdriver:
        project-id: dummy-project-id
        enabled: false
        step: PT1M

iapaudience: DUMMY

sampledefinitions:
  social: https://raw.githubusercontent.com/ONSdigital/ssdc-shared-events/main/sample/social/0.1.0/social.json
  business: https://raw.githubusercontent.com/ONSdigital/ssdc-shared-events/main/sample/business/0.1.0-DRAFT/business.json
  health: https://raw.githubusercontent.com/ONSdigital/ssdc-shared-events/main/sample/sis/0.1.0-DRAFT/sis.json


# TODO: Remove this before releasing to prod
dummyuseridentity: dummy@fake-email.com

exportfiledestinationconfigfile: dummy-export-file-destination-config.json

